source "https://rubygems.org"

ruby '3.3.5'

gem 'sinatra', '~> 2.1'
gem 'webrick'
gem 'rack-contrib', '~> 2.3'
gem 'rack-cors', '~> 1.1'
gem 'activerecord', '~> 6.1'
gem 'sinatra-activerecord', '~> 2.0'
gem 'rake', '~> 13.0'
gem 'sqlite3', '~> 1.4'
gem 'require_all', '~> 3.0'
gem 'rackup'
gem 'rack'

# Development gems
group :development do
  gem 'pry', '~> 0.14.1'
  gem 'rerun'
  gem 'rubocop'
  gem 'logger'
  gem 'ostruct'
  gem 'fiddle'
  gem 'mutex_m'
  gem 'base64'
  gem 'bigdecimal'
end

# Test gems
group :test do
  gem 'database_cleaner', '~> 2.0'
  gem 'rack-test', '~> 1.1'
  gem 'rspec', '~> 3.10'
  gem 'rspec-json_expectations', '~> 2.2'
end
