source "https://rubygems.org"

ruby "3.3.5"

gem "activerecord", "~> 6.1"
gem "rack"
gem "rack-contrib", "~> 2.3"
gem "rack-cors", "~> 1.1"
gem "rackup"
gem "rake", "~> 13.0"
gem "require_all", "~> 3.0"
gem "sinatra", "~> 2.1"
gem "sinatra-activerecord", "~> 2.0"
gem "sqlite3", "~> 1.4"
gem "webrick"

# Development gems
group :development do
  gem "base64"
  gem "bigdecimal"
  gem "fiddle"
  gem "logger"
  gem "mutex_m"
  gem "ostruct"
  gem "pry", "~> 0.14.1"
  gem "rerun"
  gem "rubocop"
end

# Test gems
group :test do
  gem "database_cleaner", "~> 2.0"
  gem "rack-test", "~> 1.1"
  gem "rspec", "~> 3.10"
  gem "rspec-json_expectations", "~> 2.2"
end

gem "rubocop-rake", "~> 0.7.1"

gem "rubocop-rspec", "~> 3.7"
